# Generated by Django 6.1.1 on 2026-09-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderitem_delete_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
