# Generated by Django 6.1.1 on 2026-09-28 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customer_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
