# Generated by Django 6.1.1 on 2026-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customeradrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeradrees',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
