# Generated by Django 6.1.1 on 2026-09-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customeradrees_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradrees',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
