# Generated by Django 6.1.1 on 2026-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customeradrees_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveBigIntegerField(),
        ),
    ]
