# Generated by Django 6.1.1 on 2026-09-30 18:27

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productrating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class, e.g. fa-solid fa-headphones', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
